#+title: Java: Thread Objects
* Concurrency
Computer users take it for granted that their systems can do more than one thing at a time. They assume that they can continue to work in a word processor, while other applications download files, manage the print queue, and stream audio. Even a single application is often expected to do more than one thing at a time. For example, that streaming audio application must simultaneously read the digital audio off the network, decompress it, manage playback, and update its display. Even the word processor should always be ready to respond to keyboard and mouse events, no matter how busy it is reformatting text or updating the display. Software that can do such things is known as concurrent software.

The Java platform is designed from the ground up to support concurrent programming, with basic concurrency support in the Java programming language and the Java class libraries. Since version 5.0, the Java platform has also included high-level concurrency APIs. This lesson introduces the platform's basic concurrency support and summarizes some of the high-level APIs in the ~java.util.concurrent~ packages.

* Processes and Threads
** Description
In concurrent programming, there are two basic units of execution: /processes/ and /threads/. In the Java programming language, concurrent programming is mostly concerned with threads. However, processes are also important.

A computer system normally has many active processes and threads. This is true even in systems that only have a single execution core, and thus only have one thread actually executing at any given moment. Processing time for a single core is shared among processes and threads through an OS feature called time slicing.

It's becoming more and more common for computer systems to have multiple processors or processors with multiple execution cores. This greatly enhances a system's capacity for concurrent execution of processes and threads — but concurrency is possible even on simple systems, without multiple processors or execution cores.

** Processes
A process has a self-contained execution environment. A process generally has a complete, private set of basic run-time resources; in particular, each process has its own memory space.

Processes are often seen as synonymous with programs or applications. However, what the user sees as a single application may in fact be a set of cooperating processes. To facilitate communication between processes, most operating systems support Inter Process Communication (IPC) resources, such as pipes and sockets. IPC is used not just for communication between processes on the same system, but processes on different systems.

Most implementations of the Java virtual machine run as a single process. A Java application can create additional processes using a ProcessBuilder object. Multiprocess applications are beyond the scope of this lesson.

** Threads
Threads are sometimes called lightweight processes. Both processes and threads provide an execution environment, but creating a new thread requires fewer resources than creating a new process.

Threads exist within a process — every process has at least one. Threads share the process's resources, including memory and open files. This makes for efficient, but potentially problematic, communication.

Multithreaded execution is an essential feature of the Java platform. Every application has at least one thread — or several, if you count "system" threads that do things like memory management and signal handling. But from the application programmer's point of view, you start with just one thread, called the main thread. This thread has the ability to create additional threads, as we'll demonstrate in the next section.

* Thread Objects
** Description
Each thread is associated with an instance of the class ~Thread~. There are two basic strategies for using ~Thread~ objects to create a concurrent application.

To directly control thread creation and management, simply instantiate ~Thread~ each time the application needs to initiate an asynchronous task.
To abstract thread management from the rest of your application, pass the application's tasks to an executor.
This section documents the use of Thread objects. Executors are discussed with other high-level concurrency objects.

An application that creates an instance of Thread must provide the code that will run in that thread. There are two ways to do this:

** Provide a Runnable Object
The ~Runnable~ interface defines a single method, ~run~, meant to contain the code executed in the thread. The ~Runnable~ object is passed to the ~Thread~ constructor, as in the ~HelloRunnable~ example:

#+begin_src java
public class HelloRunnable implements Runnable {
  @Override
  public void run() {
    System.out.println("Hello from a thread!");
  }

  public static void main(String args[]) {
    (new Thread(new HelloRunnable())).start();
  }
}
#+end_src

** Subclass Thread
 The ~Thread~ class itself implements ~Runnable~, though its ~run~ method does nothing. An application can subclass ~Thread~, providing its own implementation of ~run~, as in the ~HelloThread~ example:

 #+begin_src java
public class HelloThread extends Thread {
  @Override
  public void run() {
    System.out.println("Hello from a thread!");
  }

  public static void main(String args[]) {
    Thread helloThread = new HelloThread();
    // this runs on current thread
    helloThread.run();
    // this runs in a new thread
    helloThread.start();
  }
}
 #+end_src

** Functional interfaces
Thread creation can also be done using lambdas and method references as if they were functional programming

#+begin_src java
class Example {
  public static void main(String[] args) {
    // this creates an instance of a anonymous class which implemets
    // the Runnable interface
    Runnable runnable = new Runnable() {
      @Override
      public void run() {
        System.out.println("Hello World");
        System.out.println("Other Print");
      }
    };
    (new Thread(runnable)).start();

    // This does exactly the same but using Java's syntax sugar (lambda)
    Runnable runnable2 = () -> {
      System.out.println("Hello World");
      System.out.println("Other Print");
    };
    (new Thread(runnable2)).start()

    // we can also pass the lambda directly to the Thread constructor
    (new Thread(() -> doSomething())).start();

    // we can also pass a method reference instead of a lambda,
    // the same as the previous example
    (new Thread(Example::doSomething)).start();
  }

  static void doSomething() {
    // do something :v
    System.out.println("Hello World");
    System.out.println("Other Print");
  }
}
#+end_src
** Working example
See [[file:App.java][this file]].

* Pausing Execution with Sleep
** Description
~Thread.sleep~ causes the current thread to suspend execution for a specified period. This is an efficient means of making processor time available to the other threads of an application or other applications that might be running on a computer system. The ~sleep~ method can also be used for pacing, as shown in the example that follows, and waiting for another thread with duties that are understood to have time requirements, as with the ~SimpleThreads~ example in a later section.

Two overloaded versions of ~sleep~ are provided: one that specifies the /sleep/ time to the millisecond and one that specifies the sleep time to the nanosecond. However, these sleep times are not guaranteed to be precise, because they are limited by the facilities provided by the underlying OS. Also, the /sleep/ period can be terminated by interrupts, as we'll see in a later section. In any case, you cannot assume that invoking ~sleep~ will suspend the thread for precisely the time period specified.

The ~SleepMessages~ example uses sleep to print messages at four-second intervals:

** Example

#+begin_src java
public class SleepMessages {
    public static void main(String args[])
        throws InterruptedException {
        String importantInfo[] = {
            "Mares eat oats",
            "Does eat oats",
            "Little lambs eat ivy",
            "A kid will eat ivy too"
        };

        for (String str : importantInfo) {
          //Pause for 4 seconds
          Thread.sleep(4000);
          //Print a message
          System.out.println(str);
        }

        Consumer<String> myConsumer =
          (str) -> {
              try {
                Thread.sleep (4000);
                // print str
              } catch (InterruptedException e) {
                // no hagas nada
              }
            };

        Arrays.streams(importantInfo)
          .forEach(
          // aqui le pasamos un consumidor
            consumer
          );

    }
}
#+end_src
* Interrupts
** Description
An /interrupt/ is an indication to a thread that it should stop what it is doing and do something else. It's up to the programmer to decide exactly how a /thread/ responds to an interrupt, but it is very common for the thread to terminate. This is the usage emphasized in this lesson.

A thread sends an interrupt by invoking ~interrupt()~ on the ~Thread~ /object/ for the thread to be interrupted. For the interrupt mechanism to work correctly, the interrupted thread must support its own interruption.

** Supporting Interruption
How does a thread support its own interruption? This depends on what it's currently doing. If the thread is frequently invoking methods that throw ~InterruptedException~, it simply returns from the ~run~ method after it catches that exception. For example, suppose the central message loop in the ~SleepMessages~ example were in the ~run~ method of a thread's ~Runnable~ object. Then it might be modified as follows to support interrupts:

#+begin_src java
for (int i = 0; i < importantInfo.length; i++) {
    // Pause for 4 seconds
    try {
        Thread.sleep(4000);
    } catch (InterruptedException e) {
        // We've been interrupted: no more messages.
        return;
    }
    // Print a message
    System.out.println(importantInfo[i]);
}
#+end_src

Many methods that throw ~InterruptedException~, such as ~sleep~, are designed to cancel their current operation and return immediately when an /interrupt/ is received.

What if a /thread/ goes a long time without invoking a method that throws InterruptedException? Then it must periodically invoke ~Thread.interrupted()~, which returns ~true~ if an interrupt has been received. For example:

#+begin_src java
for (int i = 0; i < inputs.length; i++) {
    heavyCrunch(inputs[i]);
    if (Thread.interrupted()) {
        // We've been interrupted: no more crunching.
        return;
    }
}
#+end_src

In this simple example, the code simply tests for the interrupt and exits the thread if one has been received. In more complex applications, it might make more sense to throw an InterruptedException:

#+begin_src java
if (Thread.interrupted()) {
    throw new InterruptedException();
}
#+end_src

This allows interrupt handling code to be centralized in a catch clause.
** The Interrupt Status Flag
The interrupt mechanism is implemented using an internal flag known as the /interrupt status/. Invoking ~Thread.interrupt()~ sets this flag. When a thread checks for an interrupt by invoking the static method ~Thread.interrupted()~, /interrupt status/ is cleared. The non-static ~isInterrupted~ method, which is used by one thread to query the interrupt status of another, does not change the interrupt status flag.

By convention, any method that exits by throwing an ~InterruptedException~ clears /interrupt status/ when it does so. However, it's always possible that interrupt status will immediately be set again, by another thread invoking ~interrupt~.

* Joins
The ~join~ method allows one thread to wait for the completion of another. If ~t~ is a ~Thread~ /object/ whose thread is currently executing,

#+begin_src java
t.join();
#+end_src

causes the current thread to pause execution until ~t~'s thread terminates. Overloads of ~join~ allow the programmer to specify a waiting period. However, as with ~sleep~, ~join~ is dependent on the OS for timing, so you should not assume that ~join~ will wait exactly as long as you specify.

Like ~sleep~, ~join~ responds to an interrupt by exiting with an ~InterruptedException~.

* The SimpleThreads Example
The following example brings together some of the concepts of this section. ~SimpleThreads~ consists of two threads. The first is the main thread that every Java application has. The main thread creates a new thread from the ~Runnable~ object, ~MessageLoop~, and waits for it to finish. If the ~MessageLoop~ thread takes too long to finish, the main thread interrupts it.

The ~MessageLoop~ thread prints out a series of messages. If interrupted before it has printed all its messages, the ~MessageLoop~ thread prints a message and exits.

[[file:SimpleThreads.java][See code here]]
